find_path(FCGI_INCLUDE_DIR NAMES fastcgi.h PATHS /usr/include/fastcgi NO_DEFAULT_PATH)
find_library(FCGI_LIBRARY NAMES fcgi)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(FCGI DEFAULT_MSG FCGI_LIBRARY FCGI_INCLUDE_DIR)

if(FCGI_FOUND)
	set(FCGI_LIBRARIES ${FCGI_LIBRARY})
	set(FCGI_INCLUDE_DIRS ${FCGI_INCLUDE_DIR})
else()
	set(FCGI_LIBRARIES)
	set(FCGI_INCLUDE_DIRS)
endif()
mark_as_advanced(FCGI_INCLUDE_DIR FCGI_LIBRARY)
